'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Search,RefreshCw,FileText,Send,Trash2,LockKeyhole,Plus,Settings2,Check,LoaderCircle} from 'lucide-react';
import type {FeedSource,Settings,Digest,Channel} from '../lib/automation/types';
import {channelNames,deliveryNames,digestLabel,selectReport} from '../lib/automation/presentation';
import CollectionPolicyEditor from './collection-policy';
import type {CollectionPolicy} from '../lib/automation/policy';
import ReportBody from './report-body';
type Snapshot={policy?:CollectionPolicy;screening?:{configured:boolean;model:string|null};usage?:{stage:string;model:string;calls:number;promptTokens:number|null;completionTokens:number|null;unknownCalls:number}[];settings:Settings;sources:FeedSource[];digests:Digest[];deliveries:{digest_id:string;channel:Channel;status:string;error:string;attempts:number}[];services:Record<Channel|'model',boolean>;busy:boolean;suggestedFeeds:{name:string;url:string}[];runs?:{id:string;started_at:number;added:number;failures:string}[]};
type Result={message?:string;stage?:string;digestId?:string;added?:number;failures?:string[]};
type View='report'|'settings';
const dateTime=(n?:number)=>n?new Date(n).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'尚未检查';
function failures(raw:string):string[]{try{const v=JSON.parse(raw);return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string'):[];}catch{return ['记录暂时无法读取。'];}}
export default function AutomationPanel(){
  const [token,setToken]=useState(''),[draft,setDraft]=useState(''),[data,setData]=useState<Snapshot|null>(null),[settings,setSettings]=useState<Settings|null>(null);
  const [view,setView]=useState<View>('report'),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[phase,setPhase]=useState('');
  const [step,setStep]=useState<'idle'|'collect'|'generate'|'done'|'send'>('idle');
  const [notice,setNotice]=useState<{text:string;error:boolean;view:View}|null>(null);
  const [name,setName]=useState(''),[url,setUrl]=useState(''),[adding,setAdding]=useState(false);
  const request=async<T=Result>(path='',method='GET',body?:unknown,credential=token||draft):Promise<T>=>{
    let res:Response;try{res=await fetch('/api/automation'+path,{method,signal:AbortSignal.timeout(path==='/collect'?120000:path==='/report'?360000:30000),headers:{Authorization:'Bearer '+credential,...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});}catch(e){if(e instanceof Error&&['TimeoutError','AbortError'].includes(e.name))throw Error('等待响应超时，请刷新查看后台结果。推送超时后，先检查飞书群消息。');throw e;}
    let value:T & {message?:string};try{value=await res.json();}catch{throw Error(`无法读取结果（HTTP ${res.status}），请刷新。`);}if(!res.ok)throw Error(value.message||'操作失败。');return value;
  };
  const load=async(credential=token||draft)=>{const v=await request<Snapshot>('','GET',undefined,credential);setData(v);setSettings(v.settings);return v;};
  useEffect(()=>{if(!token)return;let closed=false;const timer=setInterval(()=>{if(!busy)void request<Snapshot>().then(v=>{if(!closed)setData(v);}).catch(()=>{});},data?.busy?15000:60000);return()=>{closed=true;clearInterval(timer);};},[token,busy,data?.busy]);
  const act=async(task:()=>Promise<void>)=>{setBusy(true);setNotice(null);try{await task();}catch(e){setStep('idle');await load().catch(()=>{});setNotice({text:e instanceof Error?e.message:'操作失败，请稍后重试。',error:true,view});}finally{setBusy(false);setPhase('');}};
  const generate=()=>void act(async()=>{
    setStep('collect');setPhase('正在检索订阅来源…');const collection=await request('/collect','POST');if(collection.stage==='busy')throw Error(collection.message);
    await load();setStep('generate');setPhase(`检索完成，新增 ${collection.added||0} 篇。正在合并重复资讯并生成报告…`);
    const report=await request('/report','POST');if(report.stage==='busy')throw Error(report.message);await load();if(report.digestId)setSelected(report.digestId);setStep('done');
    setNotice({text:(report.message||'已处理报告。')+(collection.failures?.length?` ${collection.failures.length} 个来源读取失败，报告范围可能不完整。`:''),error:!!collection.failures?.length,view:'report'});
  });
  const collectOnly=()=>void act(async()=>{setPhase('正在检查来源…');const result=await request('/collect','POST');await load();setNotice({text:result.message||'已检查来源。',error:!!result.failures?.length,view});});
  const current=data?selectReport(data.digests,selected):undefined;
  const row=data?.deliveries.find(d=>d.digest_id===current?.id&&d.channel==='feishu');
  const locked=busy||!!data?.busy,usable=!!current&&current.status==='ready'&&!!current.body&&!current.details?.legacyEmpty;
  const manual=!!current?.details?.manual,expired=!!current&&Date.now()-current.createdAt>=23*3600000;
  const canSend=usable&&manual&&!expired&&data?.services.feishu&&!['sent','uncertain','sending'].includes(row?.status||'')&&(row?.attempts||0)<3;
  const switchView=(next:View)=>{setView(next);setNotice(null);};
  const send=()=>void act(async()=>{if(!current)return;setStep('send');setPhase('正在推送这份报告到飞书…');const r=await request('/reports/'+encodeURIComponent(current.id)+'/send','POST');await load();setStep('done');setNotice({text:r.message||'已处理推送。',error:r.stage!=='sent',view:'report'});});
  return <div className="report-workspace"><header className="report-header"><a href="/" className="report-brand" aria-label="灵析首页"><span>析</span>灵析<small>科技聚合报告</small></a><div>{data&&<button className="text-button" disabled={busy} onClick={()=>void act(async()=>{await load();})}><RefreshCw size={15}/>刷新</button>}<button className="text-button" disabled={busy} onClick={()=>switchView(view==='report'?'settings':'report')}>{view==='settings'?<ArrowLeft size={16}/>:<Settings2 size={16}/>} {view==='settings'?'返回报告':'设置'}</button></div></header>
    <main className="report-main">{view==='report'?<>
      <div className="report-intro"><p className="report-eyebrow">少看重复报道，多看有效信息</p><h1>科技资讯，先看聚合报告。</h1><p>检索订阅来源，合并重复内容，分清事实与观点。需要深入了解时，再打开报告里的原文链接。</p></div>
      {!data&&<section className="report-connect"><LockKeyhole size={19}/><div><h2>连接你的报告空间</h2><p>输入管理口令后即可开始。口令只在本次页面内存中保存。</p><form onSubmit={e=>{e.preventDefault();if(draft&&!busy)void act(async()=>{await load(draft);setToken(draft);setDraft('');});}}><input type="password" autoComplete="off" aria-label="管理口令" placeholder="管理口令" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="primary" disabled={busy||!draft}>{busy?'正在连接…':'连接'}</button></form></div></section>}
      <section className="report-start" aria-label="检索、生成报告与推送"><div className="report-steps"><span className={step==='collect'?'active':['generate','done','send'].includes(step)?'done':''}>{['generate','done','send'].includes(step)?<Check size={16}/>:<Search size={16}/>}1. 检索资讯</span><ArrowRight size={14}/><span className={step==='generate'?'active':usable?'done':''}><FileText size={16}/>2. 生成报告</span><ArrowRight size={14}/><span className={row?.status==='sent'?'done':''}><Send size={16}/>3. 推送飞书</span></div>
        <div className="report-actions"><button className="primary report-primary" disabled={!data||locked||!data.sources.some(s=>s.enabled)||!data.services.model} onClick={generate}>{busy&&['collect','generate'].includes(step)?<LoaderCircle size={19} className="spin"/>:<Search size={19}/>} {busy&&['collect','generate'].includes(step)?'正在检索并生成…':'检索并生成报告'}</button><button className="secondary" disabled={!canSend||locked} onClick={send}><Send size={17}/>{row?.status==='sent'?'这份报告已推送':'推送这份报告到飞书'}</button></div>
        <p className="report-scope">{!data?'连接后开始检索。生成报告不会自动发送。':!data.sources.some(s=>s.enabled)?'还没有启用的来源，请到设置中添加。':!data.services.model?'模型尚未配置，请在服务端填写模型配置。':`检索范围：${data.sources.filter(s=>s.enabled).map(s=>s.name.replace(/（.*?）/g,'')).join('、')} · 报告整理最近 24 小时发布的内容。`}</p>
        {data&&<CollectionPolicyEditor policy={data.policy} screening={data.screening} locked={locked} request={request} onSaved={load}/>}
        {data&&<p className="report-action-hint">先点击“检索并生成报告”，阅读下方结果后再推送飞书。手动推送立即发送，不受每日发送时间限制。</p>}
        {busy&&phase&&<p className="report-progress" role="status"><LoaderCircle size={16} className="spin"/>{phase}</p>}{data?.busy&&!busy&&<p className="report-progress" role="status">后台正在处理，请稍后点击刷新，暂时不能重复运行。</p>}
      </section>
    </>:<div className="report-settings-heading"><h1>设置</h1><p>维护检索来源和每日自动推送。手动生成与推送从报告页开始。</p></div>}
    {notice&&notice.view===view&&<p className={`automation-notice ${notice.error?'notice-error':''}`} role={notice.error?'alert':'status'}>{notice.text}</p>}
    {view==='report'&&data&&<>{current?<article className="report-result" aria-label="聚合报告"><div className="report-result-heading"><div><p className="report-eyebrow">{manual?'本次聚合报告':current.preview?'历史预览':'每日自动报告'}</p><h2>{current.date} 科技报告</h2></div><span className="digest-state">{digestLabel(current)}</span></div><p className="digest-meta">{dateTime(current.details?.completedAt||current.createdAt)}{current.details?.eventCount!==undefined?` · ${current.details.eventCount} 条资讯`:''}{current.details?.articleCount!==undefined?` · 综合 ${current.details.articleCount} 篇文章`:''}</p>
      {current.details?.policy&&<p className="digest-meta">本报告要求：{current.details.policy.include.length?'关注 '+current.details.policy.include.join('、'):'不限关注关键词'}{current.details.policy.exclude.length?'；不关注 '+current.details.policy.exclude.join('、'):''} · 采用已有分析 {current.details.analysisReused||0} 条{current.details.filteredCount?` · 已跳过 ${current.details.filteredCount} 篇不符合要求的文章`:''}</p>}
      <p className="report-delivery">飞书：{row?deliveryNames[row.status]||row.status:'尚未推送'}{row?.error?' · '+row.error:''}</p>
      {row?.status==='uncertain'&&<p className="digest-explanation">无法确认飞书是否收到，已停止重发。请先检查群消息。</p>}
      {usable&&!manual&&<p className="digest-explanation">这是历史记录。要立即推送新报告，请点击上方“检索并生成报告”。</p>}
      {usable&&manual&&expired&&row?.status!=='sent'&&<p className="digest-explanation">报告已超过发送时限，请重新检索并生成。</p>}
      {usable&&manual&&!data.services.feishu&&<p className="digest-explanation">飞书机器人尚未配置，请在服务端填写 Webhook。</p>}
      {(row?.attempts||0)>=3&&row?.status==='error'&&<p className="digest-explanation">已达到这份报告的重试上限，请检查设置和处理记录。</p>}
      {!!current.details?.pendingCount&&<p className="digest-explanation">生成时有 {current.details.pendingCount} 篇未完成分析，未纳入本次报告。再次生成或后台任务会继续处理。</p>}
      {usable?<ReportBody body={current.body}/>:<div className="report-empty"><FileText size={28}/><h3>{digestLabel(current)==='等待分析'?'还在等待可用的分析结果':current.details?.legacyEmpty?'这是一份旧空简报':current.status==='empty'?'当前要求下暂无可用资讯':'这次没有生成报告'}</h3><p>{current.error||'点击上方“检索并生成报告”获取新的结果。没有内容的报告不会推送。'}</p></div>}
    </article>:<div className="report-empty"><FileText size={32}/><h2>报告会出现在这里</h2><p>点击上方“检索并生成报告”，查看整理后的资讯、事实与观点，以及需要时再读的原文链接。</p></div>}
    <details className="automation-details report-history"><summary>历史报告</summary><div className="digest-history-list">{data.digests.map(d=><button key={d.id} onClick={()=>{setSelected(d.id);setNotice(null);}}><span>{d.date} · {d.details?.manual?'聚合报告':d.preview?'历史预览':'每日报告'}</span><small>{digestLabel(d)}</small><time>{dateTime(d.createdAt)}</time></button>)}{!data.digests.length&&<p>暂无记录。</p>}</div></details></>}
    {view==='settings'&&!data&&<p>先返回报告页输入管理口令，再管理设置。</p>}
    <div className="report-settings automation-panel simplified-panel">
    {view==='settings'&&data&&<div id="automation-sources" ><div className="section-heading"><div><h2>订阅来源</h2><p>支持提供正文的 RSS / Atom。微信公众号需要先接入相应订阅服务。</p></div><button className="secondary" onClick={()=>setAdding(!adding)}><Plus size={15}/>{adding?'收起表单':'添加来源'}</button></div>
      {adding&&<div className="source-editor"><label>来源名称<input value={name} maxLength={60} onChange={e=>setName(e.target.value)} placeholder="例如：极客公园"/></label><label>RSS / Atom 地址<input value={url} maxLength={1500} onChange={e=>setUrl(e.target.value)} placeholder="https://…/feed"/></label><div className="source-suggestions">{data.suggestedFeeds.map(s=><button key={s.url} className="text-button" onClick={()=>{setName(s.name);setUrl(s.url);}}>{s.name}</button>)}</div><button className="primary" disabled={locked||!name.trim()||!url.trim()} onClick={()=>void act(async()=>{const result=await request('/sources','POST',{name,url});await load();setName('');setUrl('');setAdding(false);setNotice({text:result.message||'已添加。',error:false,view});})}>保存来源</button></div>}
      <div className="automation-sources">{data.sources.map(s=><div key={s.id}><div><strong>{s.name}</strong><small>{!s.enabled?'已暂停':s.error?'最近读取失败':s.lastSuccess?'最近读取成功':'等待首次检查'} · {dateTime(s.lastChecked)}</small>{s.error&&<p className="automation-error">{s.error}</p>}<details><summary>订阅地址</summary><p className="automation-url">{s.url}</p></details></div><button className={`switch ${s.enabled?'on':''}`} role="switch" aria-checked={s.enabled} aria-label={`${s.enabled?'暂停':'启用'}监听 ${s.name}`} disabled={locked} onClick={()=>void act(async()=>{await request('/sources/'+s.id,'PATCH',{enabled:!s.enabled});await load();})}><span/></button><button className="icon-button" aria-label={`删除来源 ${s.name}`} disabled={locked} onClick={()=>{if(window.confirm('删除这个订阅来源？已保存的文章会保留。'))void act(async()=>{await request('/sources/'+s.id,'DELETE',{});await load();});}}><Trash2 size={16}/></button></div>)}</div>
      <div className="section-bottom"><p>维护来源后，返回报告页开始检索并生成。</p><button className="primary" disabled={locked} onClick={()=>collectOnly()}><RefreshCw size={15}/>检查来源</button></div>
    </div>}
    {view==='settings'&&data&&settings&&<div id="automation-settings" ><div className="section-heading"><div><h2>每日自动推送</h2><p>后台定时发送的设置，不影响报告页手动推送飞书。</p></div><label className="automation-check"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>启用推送</label></div>
      <label className="automation-field">发送时间 · 北京时间<select value={settings.sendTime} onChange={e=>setSettings({...settings,sendTime:e.target.value})}>{Array.from({length:96},(_,i)=>`${String(Math.floor(i/4)).padStart(2,'0')}:${String(i%4*15).padStart(2,'0')}`).map(t=><option key={t}>{t}</option>)}</select></label><p className="automation-help">到时后的下一次后台任务会发送。平台任务执行频率决定实际发送时间。</p>
      <div className="channel-settings">{(['feishu','wecom','email'] as Channel[]).map(c=><div className="automation-channel" key={c}><label className="automation-check"><input type="checkbox" checked={settings.channels[c]} disabled={!data.services[c]&&!settings.channels[c]} onChange={e=>setSettings({...settings,channels:{...settings.channels,[c]:e.target.checked}})}/>{channelNames[c]}</label><small>{data.services[c]?'配置已填写':'尚未配置'}</small>{c==='email'&&settings.channels.email&&<label className="automation-field">收件邮箱<input type="email" maxLength={254} value={settings.emailTo} onChange={e=>setSettings({...settings,emailTo:e.target.value})} placeholder="you@example.com"/></label>}</div>)}</div><p className="automation-help">可以选择多个渠道。机器人地址和密钥保存在服务端。</p><button className="primary" disabled={locked} onClick={()=>void act(async()=>{const result=await request('/settings','PATCH',settings);await load();setNotice({text:result.message||'设置已保存。',error:false,view});})}>保存设置</button>
      <details className="automation-details"><summary>最近 24 小时的模型用量</summary><p>按服务返回的 Token 统计；失败调用可能也计费。缺少统计的调用单独列出，不按零计算。</p>{data.usage?.map(u=><p key={u.stage+u.model}>{({screen:'Jev 初筛',screen_check:'Jev 连接检查',group:'事件分组',analysis:'完整分析',policy:'要求解析'} as Record<string,string>)[u.stage]||u.stage} · {u.model} · {u.calls} 次调用 · 已知输入 {u.promptTokens??'未知'} / 输出 {u.completionTokens??'未知'} Tokens{u.unknownCalls?` · ${u.unknownCalls} 次用量未知`:''}</p>)}{!data.usage?.length&&<p>暂无统计。只记录本次更新后的服务端调用。</p>}</details>
      <details className="automation-details"><summary>服务状态</summary><p>{data.services.model?'模型配置已填写':'模型尚未配置'}。填写配置不代表每次调用一定成功，实际结果见处理记录。</p><p>{data.screening?.configured?`Jev 密钥配置已填写（${data.screening.model}）。点击下方按钮检查当前服务是否可用。`:'Jev 密钥尚未配置。'}</p><button className="secondary" disabled={locked||!data.screening?.configured} onClick={()=>void act(async()=>{setPhase('正在检查 Jev…');const result=await request('/screening/check','POST',{});await load();setNotice({text:result.message||'Jev 检查已完成。',error:false,view});})}>检查 Jev 连接</button><p className="automation-help">仅发送一段自编短文，产生一次初筛调用；不会采集、生成报告或发送消息。</p></details>
    </div>}
      {view==='settings'&&data&&<details className="automation-details"><summary>处理记录与错误详情</summary>{data.runs?.slice(0,5).map(r=><div className="collection-entry" key={r.id}><strong>{dateTime(r.started_at)} · 新增 {r.added} 篇</strong>{failures(r.failures).map((f,i)=><p className="automation-error" key={i}>{f}</p>)}</div>)}</details>}
      {view==='settings'&&data&&<button className="text-button" disabled={busy} onClick={()=>{setToken('');setDraft('');setData(null);setSettings(null);setSelected('');switchView('report');}}>退出连接</button>}
    </div></main><footer className="report-footer">灵析 · 依据来源正文整理，尚未独立核实。原始文章只在你打开链接时展示。</footer></div>;
}
