'use client';
import {useState} from 'react';
import {Radio,Mail,Clock,RefreshCw,FileText,Send,Trash2,LockKeyhole} from 'lucide-react';
import type {FeedSource,Settings,Digest,Channel} from '../lib/automation/types';
type Snapshot={settings:Settings;sources:FeedSource[];digests:Digest[];deliveries:{digest_id:string;channel:Channel;status:string;error:string;attempts:number}[];services:Record<Channel|'model',boolean>;busy:boolean;suggestedFeeds:{name:string;url:string}[];stats?:{articles:number;events:number;analyzedEvents:number;pendingArticles:number};runs?:{id:string;started_at:number;added:number;failures:string}[]};
const channelNames={email:'邮件',wecom:'企业微信机器人',feishu:'飞书机器人'};
const deliveryNames:Record<string,string>={pending:'等待发送',sending:'正在发送',sent:'发送成功',error:'发送失败',uncertain:'无法确认送达'};
const dateTime=(n?:number)=>n?new Date(n).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'尚未检查';
function failures(raw:string):string[]{try{const value=JSON.parse(raw);return Array.isArray(value)?value.filter((v):v is string=>typeof v==='string'):[];}catch{return ['这条记录无法解析，请检查后台日志。'];}}
export default function AutomationPanel(){
  const [token,setToken]=useState('');const [data,setData]=useState<Snapshot|null>(null);const [settings,setSettings]=useState<Settings|null>(null);const [name,setName]=useState('');const [url,setUrl]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [selected,setSelected]=useState<string>('');const [operation,setOperation]=useState('');
  const request=async<T={message?:string;failures?:string[]}>(path='',method='GET',body?:unknown):Promise<T>=>{
    let response:Response;
    try{response=await fetch('/api/automation'+path,{method,signal:AbortSignal.timeout(path==='/collect'?120000:['/preview','/run'].includes(path)?360000:20000),headers:{Authorization:'Bearer '+token,...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});}catch(e){if(e instanceof Error&&['TimeoutError','AbortError'].includes(e.name))throw Error('等待后台响应超时，请刷新状态查看已保存的结果，暂不要重复运行今日任务。');throw e;}
    let result:T & {message?:string};try{result=await response.json();}catch{throw Error(`后台未返回可读取的结果（HTTP ${response.status}），请刷新状态查看已保存的文章。`);}if(!response.ok)throw Error(result.message||'后台操作失败。');return result;
  };
  const load=async()=>{const result=await request() as Snapshot;setData(result);setSettings(result.settings);};
  const act=async(task:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await task();}catch(e){setMessage(e instanceof Error?e.message:'操作失败，请稍后重试。');}finally{setBusy(false);}};
  const run=(mode:string)=>{setOperation(mode);return act(async()=>{const result=await request('/'+mode,'POST');setMessage((result.message||'处理完成。')+(result.failures?.length?' 有未完成的处理，请查看下方采集记录。':''));await load();}).finally(()=>setOperation(''));};
  const current=data?.digests.find(d=>d.id===selected)||data?.digests[0];
  return <section className="automation-panel" aria-label="自动订阅与推送"><div className="automation-heading"><Radio size={22}/><div><h3>自动订阅与每日推送</h3><p>指定来源，定期收集文章，去重后把科技简报发给你。</p></div></div>
    {!data?<div className="automation-unlock"><p>这里的订阅在后台运行，关闭浏览器后也能继续。请输入管理员设置的口令，管理来源和推送。</p><div className="automation-inline"><input type="password" autoComplete="off" aria-label="自动订阅管理口令" placeholder="管理口令" value={token} onChange={e=>setToken(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&token&&!busy)void act(load);}}/><button className="primary" disabled={busy||!token} onClick={()=>void act(load)}><LockKeyhole size={14}/> {busy?'正在连接…':'打开设置'}</button></div><small>首次使用需要先由管理员配置后台服务。公众号订阅需提供 RSS/Atom 地址；仅填写名称无法读取微信文章。</small></div>:<>
    <div className="automation-status"><span>{data.services.model?'模型配置已填写':'模型尚未配置'}</span><span>{data.busy?'后台任务正在运行':settings?.enabled?'每日推送已启用':'每日推送已暂停'}</span><button className="text-button" disabled={busy} onClick={()=>void act(load)}><RefreshCw size={14}/>刷新状态</button><button className="text-button" onClick={()=>{setData(null);setSettings(null);setToken('');}}>退出管理</button></div>
    {data.stats&&<p className="automation-help">已保存 {data.stats.articles} 篇文章 · 已整理 {data.stats.events} 个事件 · {data.stats.analyzedEvents} 个事件已分析 · {data.stats.pendingArticles} 篇正文待分析。待分析文章可在自动阅读工作台查看，不会显示假评分。</p>}
    <div className="automation-grid"><div><h4>监听哪些来源</h4><p className="automation-help">公众号 RSS、网站 RSS 或 Atom 都可以。订阅源需要提供正文；只有短摘要的文章会保留链接，并注明未作评分。</p><div className="automation-source-form"><label>公众号 / 来源名称<input value={name} maxLength={60} onChange={e=>setName(e.target.value)} placeholder="例如：量子位"/></label><label>订阅地址<input value={url} maxLength={1500} onChange={e=>setUrl(e.target.value)} placeholder="https://…/feed"/></label><button className="secondary" disabled={busy||data.busy||!name.trim()||!url.trim()} onClick={()=>void act(async()=>{const result=await request('/sources','POST',{name,url});await load();setName('');setUrl('');setMessage(result.message||'设置已保存。');})}>添加订阅源</button></div>
    <div className="automation-suggestions"><small>可先试试这些公开网站订阅（不等同于微信账号监听）：</small>{data.suggestedFeeds.map(s=><button key={s.url} className="text-button" onClick={()=>{setName(s.name);setUrl(s.url);}}>{s.name}</button>)}</div>
    <div className="automation-sources">{data.sources.map(s=><div key={s.id}><div><strong>{s.name}</strong><p className="automation-url">{s.url}</p><small>上次检查：{dateTime(s.lastChecked)}{s.lastSuccess?` · 最近成功：${dateTime(s.lastSuccess)}`:''}</small>{s.error&&<p className="automation-error">{s.error}</p>}</div><button className={`switch ${s.enabled?'on':''}`} role="switch" aria-checked={s.enabled} aria-label={`${s.enabled?'暂停':'启用'}监听 ${s.name}`} disabled={busy||data.busy} onClick={()=>void act(async()=>{await request('/sources/'+s.id,'PATCH',{enabled:!s.enabled});await load();})}><span/></button><button className="icon-button" aria-label={`删除来源 ${s.name}`} disabled={busy||data.busy} onClick={()=>{if(window.confirm('停止监听并删除来源配置？已采集文章和历史事件会保留。'))void act(async()=>{await request('/sources/'+s.id,'DELETE',{});await load();});}}><Trash2 size={15}/></button></div>)}{!data.sources.length&&<p className="automation-help">还没有订阅源，添加一个后可以立即检查。</p>}</div></div>
    {settings&&<div><h4>什么时候发，发到哪里</h4><label className="automation-check"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>启用每日推送</label><label className="automation-field"><Clock size={14}/>发送时间（北京时间）<select value={settings.sendTime} onChange={e=>setSettings({...settings,sendTime:e.target.value})}>{Array.from({length:96},(_,i)=>`${String(Math.floor(i/4)).padStart(2,'0')}:${String(i%4*15).padStart(2,'0')}`).map(t=><option key={t}>{t}</option>)}</select></label><p className="automation-help">后台按部署的定时任务检查来源；执行频率以部署平台设置为准，到发送时间后的下一次任务会处理尚未发送的文章，迟到文章和超量文章会继续排队。每个渠道每天发送一次简报。</p>
    {(['email','wecom','feishu'] as Channel[]).map(c=><div className="automation-channel" key={c}><label className="automation-check"><input type="checkbox" checked={settings.channels[c]} onChange={e=>setSettings({...settings,channels:{...settings.channels,[c]:e.target.checked}})}/>{channelNames[c]}</label><small>{data.services[c]?'发送配置已填写':'管理员尚未配置这个渠道'}</small>{c==='email'&&settings.channels.email&&<label className="automation-field"><Mail size={14}/>收件邮箱<input type="email" maxLength={254} value={settings.emailTo} onChange={e=>setSettings({...settings,emailTo:e.target.value})} placeholder="you@example.com"/></label>}</div>)}<p className="automation-help">机器人地址和邮件密钥只保存在服务端，不会显示在这里。可以同时选择多个渠道。</p><button className="primary" disabled={busy||data.busy} onClick={()=>void act(async()=>{const result=await request('/settings','PATCH',settings);await load();setMessage(result.message||'设置已保存。');})}>保存推送设置</button></div>}</div>
    <div className="automation-actions"><button className="secondary" disabled={busy||data.busy} onClick={()=>run('collect')}><RefreshCw size={14}/>检查新文章</button><button className="secondary" disabled={busy||data.busy} onClick={()=>run('preview')}><FileText size={14}/>生成预览（不发送）</button><button className="secondary" disabled={busy||data.busy||!data.settings.enabled} onClick={()=>run('run')}><Send size={14}/>运行今日任务</button>{busy&&<span role="status">{operation==='collect'?'正在检查订阅并保存文章，不等待模型分析…':'正在整理事件；模型分析可能需要几分钟…'}</span>}</div><p className="automation-help">“运行今日任务”遵循已保存的发送时间和开关，不会提前发送。“检查新文章”只采集和保存，模型分组与分析由后续后台任务处理。预览使用最近 24 小时的文章，不占用当天的正式推送。</p>
    <div className="automation-history"><h4>最近采集记录</h4>{data.runs?.length?data.runs.slice(0,5).map(run=><div key={run.id}><p>{dateTime(run.started_at)} · 新增 {run.added} 篇{run.added===0?'（没有新文章或已入库，具体失败见下方）':''}</p>{failures(run.failures).map((failure,i)=><p className="automation-error" key={i}>{failure}</p>)}</div>):<p className="automation-help">还没有完成的采集记录。检查完成后会显示新增数量及失败原因。</p>}</div>
    <div className="automation-history"><h4>最近简报与发送记录</h4>{!!data.digests.length&&<select aria-label="选择历史简报" value={current?.id||''} onChange={e=>setSelected(e.target.value)}>{data.digests.map(d=><option key={d.id} value={d.id}>{d.date} · {d.preview?'预览':'每日推送'} · {d.status==='ready'?'已生成':d.status==='error'?'生成失败':'生成中'}</option>)}</select>}{current?<><p className="automation-help">生成时间：{dateTime(current.createdAt)}{current.preview?' · 本次预览没有发送':''}</p>{current.error&&<p className="automation-error">{current.error}</p>}<div className="automation-deliveries">{data.deliveries.filter(d=>d.digest_id===current.id).map(d=><p key={d.channel}><strong>{channelNames[d.channel]}</strong> · {deliveryNames[d.status]||d.status}{d.attempts?` · 尝试 ${d.attempts} 次`:''}{d.error&&<span> — {d.error}</span>}</p>)}</div>{current.body&&<pre className="automation-brief">{current.body}</pre>}</>:<p className="automation-help">采集后生成预览，即可在这里查看去重后的简报。</p>}</div>
    </>}{message&&<p className="automation-message" role="status">{message}</p>}</section>;
}
