'use client';
import {useState} from 'react';
import type {CollectionPolicy} from '../lib/automation/policy';
const initial:CollectionPolicy={instruction:'',include:[],exclude:[],screenEnabled:true,minValue:40,deepLimit:6};
export default function CollectionPolicyEditor({policy,screening,locked,request,onSaved}:{policy?:CollectionPolicy;screening?:{configured:boolean;model:string|null};locked:boolean;request:<T>(path:string,method:string,body:unknown)=>Promise<T>;onSaved:()=>Promise<unknown>}){
  const [draft,setDraft]=useState<CollectionPolicy>(policy||initial),[working,setWorking]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
  const [includeText,setIncludeText]=useState((policy?.include||[]).join('、')),[excludeText,setExcludeText]=useState((policy?.exclude||[]).join('、'));
  const disabled=locked||working,summary=[policy?.include.length?'关注 '+policy.include.join('、'):'不限关注关键词',policy?.exclude.length?'不关注 '+policy.exclude.join('、'):''].filter(Boolean).join('；');
  const run=async(task:()=>Promise<void>)=>{setWorking(true);setMessage('');setError(false);try{await task();}catch(e){setError(true);setMessage(e instanceof Error?e.message:'保存失败。');}finally{setWorking(false);}};
  const split=(value:string)=>value.split(/[,，、;；\n]/).map(s=>s.trim()).filter(Boolean);
  return <details className="automation-details collection-policy"><summary>搜集要求 · {summary}</summary><p>先解析并检查关键词，再保存。要求用于订阅文章的筛选；不会搜索整个互联网。已生成的报告保留当时的要求。</p>
    <label className="automation-field">用一句话说明<textarea rows={2} maxLength={500} disabled={disabled} placeholder="例如：关注 AI 和芯片，不关注汽车手机" value={draft.instruction} onChange={e=>setDraft({...draft,instruction:e.target.value})}/></label>
    <button className="secondary" disabled={disabled} onClick={()=>void run(async()=>{const parsed=await request<{include:string[];exclude:string[];method:string}>('/policy/parse','POST',{instruction:draft.instruction});setDraft({...draft,include:parsed.include,exclude:parsed.exclude});setIncludeText(parsed.include.join('、'));setExcludeText(parsed.exclude.join('、'));setMessage(parsed.method+'完成，请检查下方关键词并保存。');})}>{working?'正在处理…':'解析要求'}</button>
    <div className="policy-keywords"><label className="automation-field">关注关键词 · 留空表示不限<input disabled={disabled} maxLength={1200} value={includeText} onChange={e=>{setIncludeText(e.target.value);setDraft({...draft,include:split(e.target.value)});}} placeholder="AI、芯片"/></label><label className="automation-field">排除关键词 · 排除优先<input disabled={disabled} maxLength={1200} value={excludeText} onChange={e=>{setExcludeText(e.target.value);setDraft({...draft,exclude:split(e.target.value)});}} placeholder="汽车、手机"/></label></div>
    <p>汽车、手机、AI、芯片会匹配常见相关词；其他关键词按标题和开头内容匹配。排除规则可能连同多主题早报一起过滤，请按需要调整。</p>
    <details><summary>减少模型开销</summary><label className="automation-check"><input type="checkbox" disabled={disabled} checked={draft.screenEnabled} onChange={e=>setDraft({...draft,screenEnabled:e.target.checked})}/>先用 Jev 初筛阅读价值</label><p>{screening?.configured?`Jev 配置已填写（${screening.model}）。每轮最多初筛 12 篇，仅发送标题和 300 字摘录。把握不足时保留文章。`:'尚未填写 JEV_API_KEY，目前只做免费的关键词筛选，然后直接分析。'}初筛判断不等于核实事实。</p><label className="automation-field">初筛最低阅读价值 · 0–100<input type="number" min={0} max={100} disabled={disabled} value={draft.minValue} onChange={e=>setDraft({...draft,minValue:Number(e.target.value)})}/></label><label className="automation-field">每轮最多完整分析几个事件<select disabled={disabled} value={draft.deepLimit} onChange={e=>setDraft({...draft,deepLimit:Number(e.target.value)})}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><p>其他文章留到后续处理。内容和分组没有变化的事件会使用已有分析。</p></details>
    <button className="primary" disabled={disabled} onClick={()=>void run(async()=>{const result=await request<{message:string}>('/policy','PATCH',draft);await onSaved();setMessage(result.message);})}>保存并应用</button>{message&&<p className={error?'automation-error':'automation-help'} role={error?'alert':'status'}>{message}</p>}
  </details>;
}
