'use client';
import {useEffect,useState} from 'react';
import type {CollectionPolicy} from '../lib/automation/policy';
import {channelNames,deliveryNames,digestLabel,selectReport} from '../lib/automation/presentation';
import {formatTime,type Snapshot,type ClientRequest} from '../lib/client-feed';
import type {Channel} from '../lib/automation/types';
import ReportBody from './report-body';

export default function FeedSettings({data,locked,request,refresh,generate,savePolicy,disconnect}:{data:Snapshot;locked:boolean;request:ClientRequest;refresh:()=>Promise<void>;generate:()=>Promise<string|undefined>;savePolicy:(p:CollectionPolicy)=>Promise<void>;disconnect:()=>void}){
 const [draft,setDraft]=useState(data.settings),[working,setWorking]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(false),[selected,setSelected]=useState('');
 const [name,setName]=useState(''),[url,setURL]=useState(''),[budget,setBudget]=useState(data.policy);
 const dirty=JSON.stringify(draft)!==JSON.stringify(data.settings)||!!name||!!url||budget.screenEnabled!==data.policy.screenEnabled||budget.minValue!==data.policy.minValue||budget.deepLimit!==data.policy.deepLimit;
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const disabled=locked||working,current=selectReport(data.digests,selected),row=data.deliveries.find(d=>d.digest_id===current?.id&&d.channel==='feishu');
 const canSend=current?.status==='ready'&&!!current.body&&current.details?.manual&&!current.details.legacyEmpty&&Date.now()-current.createdAt<23*3600000&&data.services.feishu&&!['sent','sending','uncertain'].includes(row?.status||'')&&(row?.attempts||0)<3;
 const act=async(task:()=>Promise<void>)=>{setWorking(true);setNotice('');setError(false);try{await task();}catch(e){setError(true);setNotice(e instanceof Error?e.message:'操作失败。');}finally{setWorking(false);}};
 return <div className="feed-settings"><div className="settings-feedback">{working&&<p role="status" className="feed-help">正在处理，请稍候…</p>}{notice&&<p className={error?'feed-error':'feed-notice'} role={error?'alert':'status'}>{notice}</p>}</div><section><h3>机器人推送</h3><label className="feed-check"><input type="checkbox" checked={draft.enabled} disabled={disabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>启用每日自动推送</label><label className="feed-field">发送时间（北京时间）<select name="sendTime" value={draft.sendTime} disabled={disabled} onChange={e=>setDraft({...draft,sendTime:e.target.value})}>{Array.from({length:96},(_,i)=>`${String(Math.floor(i/4)).padStart(2,'0')}:${String(i%4*15).padStart(2,'0')}`).map(t=><option key={t}>{t}</option>)}</select></label><p className="feed-help">到时后的下一次后台任务发送，实际时间取决于平台执行频率。</p>
 {(['feishu','wecom'] as Channel[]).map(channel=>{const latest=data.deliveries.filter(d=>d.channel===channel).sort((a,b)=>(b.started_at||0)-(a.started_at||0))[0];return <div className="robot-setting" key={channel}><label className="feed-check"><input type="checkbox" checked={draft.channels[channel]} disabled={disabled||(!data.services[channel]&&!draft.channels[channel])} onChange={e=>setDraft({...draft,channels:{...draft.channels,[channel]:e.target.checked}})}/>{channelNames[channel]}</label><p>{data.services[channel]?'配置已填写':'未配置'} / {data.settings.enabled&&data.settings.channels[channel]?'自动推送已开启':'自动推送已关闭'}</p><p>最近发送：{latest?deliveryNames[latest.status]||'状态未知':'暂无发送记录'}{latest?.started_at?'（'+formatTime(latest.started_at)+'）':''}</p>{latest&&<small>报告：{data.digests.find(d=>d.id===latest.digest_id)?.date||latest.digest_id}</small>}{latest?.error&&<p className="feed-error">{latest.error}</p>}{latest?.status==='uncertain'&&<p className="feed-help">请先检查群消息，系统不会自动重发。</p>}</div>;})}
 <details><summary>配置说明与其他渠道</summary><p className="feed-help">企业微信支持群机器人，暂不支持个人微信。Webhook 保存在服务端 Secrets，不能在这里修改。配置已填写不等于送达成功；已发送表示服务接受了请求。</p><label className="feed-check"><input type="checkbox" checked={draft.channels.email} disabled={disabled||(!data.services.email&&!draft.channels.email)} onChange={e=>setDraft({...draft,channels:{...draft.channels,email:e.target.checked}})}/>邮件</label>{draft.channels.email&&<label className="feed-field">收件邮箱<input name="emailTo" type="email" spellCheck={false} autoComplete="email" maxLength={254} value={draft.emailTo} disabled={disabled} onChange={e=>setDraft({...draft,emailTo:e.target.value})}/></label>}</details><button className="feed-primary" disabled={disabled} onClick={()=>void act(async()=>{const r=await request('/settings','PATCH',draft);await refresh();setNotice(r.message||'推送设置已保存。');})}>保存推送设置</button>
 </section>
 <details className="settings-section"><summary>订阅来源</summary><p className="feed-help">提供正文的 RSS / Atom。保存偏好不会重新读取这些来源。</p>{data.sources.map(s=><div key={s.id} className="source-setting"><label className="feed-check"><input type="checkbox" checked={s.enabled} disabled={disabled} onChange={()=>void act(async()=>{await request('/sources/'+s.id,'PATCH',{enabled:!s.enabled});await refresh();setNotice('来源状态已更新。');})}/>{s.name}</label><small>{s.error?'最近读取失败':s.lastSuccess?'最近读取成功':'等待首次检查'}{s.lastChecked?'（'+formatTime(s.lastChecked)+'）':''}</small>{s.error&&<p className="feed-error">{s.error}</p>}<details><summary>订阅地址</summary><p className="feed-help break-word">{s.url}</p></details></div>)}<form onSubmit={e=>{e.preventDefault();if(!disabled)void act(async()=>{const r=await request('/sources','POST',{name,url});await refresh();setName('');setURL('');setNotice(r.message||'来源已添加。');});}}><label className="feed-field">新来源名称<input name="sourceName" autoComplete="off" maxLength={60} required value={name} disabled={disabled} onChange={e=>setName(e.target.value)}/></label><label className="feed-field">RSS / Atom 地址<input name="sourceURL" type="url" autoComplete="url" required maxLength={1500} value={url} disabled={disabled} onChange={e=>setURL(e.target.value)} placeholder="https://example.com/feed"/></label><button className="feed-secondary" disabled={disabled||!name.trim()||!url.trim()}>添加来源</button></form></details>
 <details className="settings-section"><summary>报告与服务</summary><p className="feed-help">“检查新资讯并分析”会读取来源、使用模型并生成报告，不会自动发送消息。其他文章可能需要后续任务继续处理。</p><button className="feed-primary" disabled={disabled||!data.services.model||!data.sources.some(s=>s.enabled)} onClick={()=>void act(async()=>{const id=await generate();setSelected(id||'');setNotice('处理结束，请查看报告状态与未完成说明。');})}>检查新资讯并分析</button>{current&&<div className="settings-report"><h3>{current.date} 科技报告</h3><p className="feed-help">{digestLabel(current)} / 飞书：{row?deliveryNames[row.status]||'状态未知':'尚未推送'}</p>{current.details?.policy&&<p className="feed-help">报告当时的偏好：关注 {current.details.policy.include.join('、')||'不限'}；不看 {current.details.policy.exclude.join('、')||'无'}。</p>}{current.details?.pendingCount? <p className="feed-help">有 {current.details.pendingCount} 篇未完成分析，未包含在这份报告中。</p>:null}{current.error&&<p className="feed-error">{current.error}</p>}{row?.error&&<p className="feed-error">{row.error}</p>}{current.status==='ready'&&current.body?<details><summary>阅读这份报告</summary><ReportBody body={current.body}/></details>:<p className="feed-help">当前没有可用报告，不会发送。</p>}<button className="feed-secondary" disabled={disabled||!canSend} onClick={()=>void act(async()=>{if(!current)return;const r=await request('/reports/'+encodeURIComponent(current.id)+'/send','POST');await refresh();setError(r.stage!=='sent');setNotice(r.message||'请查看实际发送记录。');})}>推送这份报告到飞书</button>{current.status==='ready'&&!canSend&&<p className="feed-help">只发送未过期、尚未发送的手动报告。送达不明、发送中或达到重试上限时不重发。</p>}</div>}
 <details><summary>历史报告</summary>{data.digests.map(d=><button className="report-history-entry" key={d.id} onClick={()=>setSelected(d.id)}>{d.date} / {digestLabel(d)}<small>{formatTime(d.createdAt)}</small></button>)}{!data.digests.length&&<p>暂无记录。</p>}</details>
 <p className="feed-help">{data.services.model?'分析模型配置已填写':'分析模型未配置'}；{data.screening?.configured?`Jev 配置已填写（${data.screening.model}）`:'Jev 未配置'}。配置存在不代表每次调用成功。</p><button className="feed-secondary" disabled={disabled||!data.screening?.configured} onClick={()=>void act(async()=>{const r=await request('/screening/check','POST',{});await refresh();setNotice(r.message||'连接检查已完成。');})}>检查 Jev 连接</button><p className="feed-help">连接检查只发送自编短文，会产生一次初筛调用。</p>
 <details><summary>模型用量与预算</summary><label className="feed-check"><input type="checkbox" checked={budget.screenEnabled} disabled={disabled} onChange={e=>setBudget({...budget,screenEnabled:e.target.checked})}/>先用 Jev 初筛</label><label className="feed-field">初筛最低阅读价值<input name="minValue" type="number" min={0} max={100} value={budget.minValue} disabled={disabled} onChange={e=>setBudget({...budget,minValue:Number(e.target.value)})}/></label><label className="feed-field">每轮最多完整分析的事件<select name="deepLimit" value={budget.deepLimit} disabled={disabled} onChange={e=>setBudget({...budget,deepLimit:Number(e.target.value)})}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><button className="feed-secondary" disabled={disabled} onClick={()=>void act(async()=>{await savePolicy({...data.policy,screenEnabled:budget.screenEnabled,minValue:budget.minValue,deepLimit:budget.deepLimit});setNotice('模型预算已保存。');})}>保存模型预算</button>{data.usage?.map(u=><p className="feed-help" key={u.stage+u.model}>{({policy:'偏好解析',screen:'Jev 初筛',screen_check:'Jev 连接检查',group:'事件分组',analysis:'完整分析'} as Record<string,string>)[u.stage]||u.stage}：{u.calls} 次，输入 {u.promptTokens??'未知'} / 输出 {u.completionTokens??'未知'} Tokens；{u.unknownCalls} 次用量未知。</p>)}</details></details>
 <p className="feed-help">偏好会影响此私人站点后续生成的报告与推送。第一版尚未实现多用户独立设置。</p><button className="feed-text" disabled={disabled} onClick={disconnect}>退出连接</button>
 </div>;
}
